### ISSUE TITLE
Set cgroups command to launch Flink stream applications

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/explore-flink#15]
We need to launch stream applications using `cgroups` in order to be able to set different quotas to each operator. It is necessary to add the command `cgexec -g "cpulimited" <COMMAND to launch stream application>`  on the launch.sh script and test it.

**Comment by abelpc** [comment]
Is the following link somehow related? https://cwiki.apache.org/confluence/pages/viewpage.action?spm=a2c65.11461447.0.0.3bb3582dXndn6v&pageId=65147077

**Comment by felipegutierrez** [comment]
Somehow. For instance, when we deploy flink on Mesos and we have none application running we see none task managers available. Only when we deploy a stream application somehow the task managers appear. This is referred to as the dynamic resource allocation.

The farthest that Flink goes is defining Slots in each task manager. Then we can place a number of threads/operators in the slots [Task chaining and resource groups](https://ci.apache.org/projects/flink/flink-docs-stable/dev/stream/operators/#task-chaining-and-resource-groups).
